; BIND reverse data file for empty rfc1918 zone
;
; DO NOT EDIT THIS FILE - it is used for multiple zones.
; Instead, copy it, edit named.conf, and use that copy.
;
$TTL	86400
@	IN	SOA	example.com.	admin.example.com. (
			      1		; Serial
			 604800		; Refresh
			  86400		; Retry
			2419200		; Expire
			  86400 )	; Negative Cache TTL
;
@	IN	NS	dns1.example.com.
		A	192.168.122.8

$ORIGIN example.com.
dns1	IN	A	192.168.122.8
dns2	IN	A	192.168.122.4
db	IN	A	192.168.122.31
web1	IN	A	192.168.122.21
web2	IN	A	192.168.122.22
bastion	IN	A	192.168.122.68
ipa	IN	A	192.168.122.11
monitor	IN	A	192.168.122.12
